force-app/main/SDO_SCOM_PRODUCT_REVIEWS/objects/SDO_SCOM_Customer_Review__c/SDO_SCOM_Customer_Review__c.object-meta.xml
<CustomObject>
    <label>SDO_SCOM_Customer_Review</label>
    <nameField>
        <label>Customer Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SDO_SCOM_Customer_Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/SDO_SCOM_PRODUCT_REVIEWS/objects/SDO_SCOM_Customer_Review__c/fields/Product_Rating__c.field-meta.xml
<CustomField>
    <fullName>Product_Rating__c</fullName>
    <description>Product Rating added by Customers between 0-5</description>
    <label>Product_Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/SDO_SCOM_PRODUCT_REVIEWS/objects/SDO_SCOM_Customer_Review__c/fields/Product_Review_Date__c.field-meta.xml
<CustomField>
    <fullName>Product_Review_Date__c</fullName>
    <label>Product_Review_Date</label>
    <type>Date</type>
</CustomField>

force-app/main/SDO_SCOM_PRODUCT_REVIEWS/objects/SDO_SCOM_Customer_Review__c/fields/Product_Review_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Review_Description__c</fullName>
    <description>Description of the Review written by the Customer</description>
    <label>Product_Review_Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/SDO_SCOM_PRODUCT_REVIEWS/objects/SDO_SCOM_Customer_Review__c/fields/Product_Review_Title__c.field-meta.xml
<CustomField>
    <fullName>Product_Review_Title__c</fullName>
    <description>Title of the Review added by Customer</description>
    <label>Product_Review_Title</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/SDO_SCOM_PRODUCT_REVIEWS/classes/Sdo_scom_product_reviews.cls
public with sharing class Sdo_scom_product_reviews {
    public Sdo_scom_product_reviews() {}

    @AuraEnabled(cacheable=true)
    public static List<SDO_SCOM_Customer_Review__c> getCustomObjects() {
        return [
            SELECT Id, 	Username__c, Product_Review_Date__c, Product_Rating__c, Product_Review_Title__c, Product_Review_Description__c 
            FROM SDO_SCOM_Customer_Review__c 
        ];
    }
}